FROM node:18.14.2 as tailwind

ARG APP_HOME=/app

WORKDIR ${APP_HOME}

COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

COPY ./applications/user ${APP_HOME}

RUN npm run build

FROM python:3.11-alpine

ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR ${APP_HOME}

RUN apk add --no-cache --upgrade bash jq curl

COPY ./applications/user/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY --from=tailwind ${APP_HOME} ${APP_HOME}

COPY ./docker/script/dj_entry /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/script/dj_start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start


ENTRYPOINT [ "/entrypoint" ]
CMD [ "/start" ]