FROM python:3.11-alpine

ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

RUN apk add --no-cache --upgrade bash jq curl

COPY ./applications/job/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./applications/job ${APP_HOME}

COPY ./docker/script/dj_entry /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/script/dj_job_start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start


ENTRYPOINT [ "/entrypoint" ]
CMD [ "/start" ]