# Generated by Django 4.2.7 on 2023-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailregion",
            name="name",
            field=models.CharField(max_length=50, verbose_name="세부지역명"),
        ),
    ]
