# Generated by Django 4.2.7 on 2023-11-16 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruit",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="recruit",
            name="job_recruit_created_0808d5_idx",
        ),
    ]
