# Generated by Django 4.2.7 on 2023-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_alter_recruit_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="preference",
            field=models.TextField(blank=True, null=True, verbose_name="우대사항"),
        ),
    ]
