# Generated by Django 4.2.7 on 2023-11-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_recruit_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="카테고리명"),
        ),
    ]
