# Generated by Django 4.2.6 on 2023-11-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.CharField(max_length=30, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=30, unique=True, verbose_name="휴대폰번호"),
        ),
    ]
