# Generated by Django 4.2.6 on 2023-10-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신일")),
                ("nick_name", models.CharField(max_length=30)),
                ("prefix", models.CharField(max_length=50)),
                ("creator_id", models.IntegerField()),
                ("target_url", models.CharField(max_length=1000)),
                ("click", models.BigIntegerField(default=0)),
                ("shortened_url", models.CharField(max_length=6)),
                ("last_clicked", models.DateTimeField(null=True)),
                ("expired_at", models.DateField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prefix", "shortened_url"],
                        name="url_shorten_prefix_5381a3_idx",
                    )
                ],
            },
        ),
    ]
