# Generated by Django 4.2.6 on 2023-11-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="access",
            field=models.IntegerField(
                choices=[(1, "Public"), (2, "Private"), (3, "Secret")],
                default=1,
                verbose_name="공개범위",
            ),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="click",
            field=models.BigIntegerField(default=0, verbose_name="클릭 수"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="creator_id",
            field=models.IntegerField(verbose_name="생성자 ID"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="expired_at",
            field=models.DateField(null=True, verbose_name="만료일"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="last_clicked",
            field=models.DateTimeField(null=True, verbose_name="마지막 클릭 일시"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="nick_name",
            field=models.CharField(max_length=30, verbose_name="별칭"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="prefix",
            field=models.CharField(max_length=50, verbose_name="접두사"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url",
            field=models.CharField(max_length=6, verbose_name="단축 url"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="target_url",
            field=models.CharField(max_length=1000, verbose_name="대상 URL"),
        ),
    ]
