# Generated by Django 4.2.6 on 2023-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url", "0002_shortenedurl_access_alter_shortenedurl_click_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortenedurl",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="nick_name",
            field=models.CharField(
                default="Undefined", max_length=30, verbose_name="별칭"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedurl",
            index=models.Index(
                fields=["-created_at"], name="url_shorten_created_07583b_idx"
            ),
        ),
    ]
