# Generated by Django 4.2.6 on 2023-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url", "0003_alter_shortenedurl_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="expired_at",
            field=models.DateField(blank=True, null=True, verbose_name="만료일"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="nick_name",
            field=models.CharField(
                blank=True, default="Undefined", max_length=30, verbose_name="별칭"
            ),
        ),
    ]
