#!/bin/bash

# static data crawling 진행
echo "static data crawling 진행"
python manage.py 01_job_group
python manage.py 02_job_category
python manage.py 03_country
python manage.py 04_region
python manage.py 05_detail_region

# collectstatic 진행
echo "collectstatic 진행"
python manage.py collectstatic --no-input

# migrate 진행
echo "migrate 진행"
python manage.py migrate

# gunicorn 실행
echo "gunicorn 실행"
gunicorn config.wsgi:application -c config/gunicorn_config.py