#!/bin/bash

sed -i "s/USER_SERVICE_HOST/$USER_SERVICE_HOST/g" /etc/nginx/sites-available/django
sed -i "s/URL_SERVICE_HOST/$URL_SERVICE_HOST/g" /etc/nginx/sites-available/django
service nginx restart